openshift/distributed-tracing-console-plugin

- README.md
- locales/en/plugin__distributed-tracing-console-plugin.json
- package.json
- src/components/PersesWrapper.tsx
- src/components/TraceQueryBrowser.css
- src/components/TraceQueryBrowser.tsx
- src/components/TraceTable.tsx
- src/components/TracingPage.tsx
- start-console.sh
- tsconfig.json
- yarn.lock
Initial MVP of distributed-tracing-console-plugin. 
- Perses Scatterplot 
- TraceQL input (no autocomplete/formatting, will be implemented later with Lezer) 
- Patternfly Table
- [OU-325: Integrate PersesUI scatter plot plugins into the distributed tracing plugin](https://issues.redhat.com/browse/OU-325)
- [OU-159: Integrate a TraceQL input](https://issues.redhat.com/browse/OU-159)
- [OU-195: Integrate a TraceQL results table in the distributed tracing plugin](https://issues.redhat.com/browse/OU-195)
> OU-325: OU-159: OU-195: Initial MVP of Tracing Plugin 

- hack/deploy-test-instance.sh
- scripts/build-dev-image.sh
- web/package.json
- web/src/cancellable-fetch.ts
- web/src/components/PersesWrapper.tsx
- web/src/components/TraceQueryBrowser.tsx
- web/src/components/TracingPage.tsx
- web/src/hooks/useTempoStack.ts
Fix: 
- Remove plugin_backend binary, 
- adjust npm run lint command in package.json, 
- run `make lint-frontend`, 
- update hack scripts to `oc login` before opening the console in a web browser
> Remove plugin_backend binary, Adjust `lint` command 

- charts/distributed-tracing-console-plugin/templates/consoleplugin.yaml
- hack/distributed-tracing-console-plugin-resources.yaml
- web/src/components/PersesWrapper.tsx
- Add proxy service in ConsolePlugin CRD
- Update frontend to use proxy service endpoint at /api/proxy/plugin/distributed-tracing-console-plugin/backend
- Remove trailing spaces next to 'proxy: ' from CRDs
Note: Revert of previous commit needs to be done first https://github.com/openshift/distributed-tracing-console-plugin/pull/14
> Fix querier by adding proxy service provided in ConsolePlugin CRD 

- web/i18n-scripts/build-i18n.sh
- web/i18n-scripts/common.js
- web/i18n-scripts/lexers.js
- web/i18n-scripts/set-english-defaults.js
- web/locales/en/plugin__distributed-tracing-console-plugin.json
- web/package-lock.json
- web/package.json
- web/src/components/TraceEmptyState.tsx
- web/src/components/TracingPage.tsx
- Update description of the tracing page when there is no Tempo Stack selected
- Add/standardize i18n files to mimic troubleshooting-panel-console-plugin
> OU-452: Fix initial state to be more descriptive in distributed-tracing-console-plugin

- web/src/components/TempoStackDropdown.tsx
- web/src/components/TracingPage.tsx
- web/src/hooks/useTempoStack.ts
> OU-458: move the trace pages initial loading state to the tempo stack dropdown

- Makefile
- scripts/start-backend.sh
- scripts/start-console.sh
- web/i18n-scripts/build-i18n.sh
- web/i18n-scripts/common.js
- web/i18n-scripts/lexers.js
- web/i18n-scripts/set-english-defaults.js
- web/locales/en/plugin__distributed-tracing-console-plugin.json
- web/package-lock.json
- web/package.json
- web/src/components/DurationDropdown.tsx
- web/src/components/PersesWrapper.tsx
- web/src/components/TempoStackDropdown.tsx
- web/src/components/TraceEmptyState.tsx
- web/src/components/TraceTable.tsx
- web/src/components/TracingPage.tsx
Manual cherry-pick of [PR#18](https://github.com/openshift/distributed-tracing-console-plugin/pull/18/commits) bea3fa4afe936b82ced05fc482c78aeadc607fed
Manual cherry-pick of [PR#21 ](https://github.com/openshift/distributed-tracing-console-plugin/pull/21/commits) 7e68eda0af789a3627d381f311df6cb22b67eb9e
> Manual cherry pick PR#18 PR#21

- web/src/components/TempoStackDropdown.tsx
- web/src/hooks/useTempoStack.ts
This PR adds validation to the tempo stack list as it could return results in a different format, due to the proxy failing or not found resources.
> COO-216: validate the tempo list response

- web/.prettierrc.yml
- web/src/TracingUI.tsx
- web/src/cancellable-fetch.ts
- web/src/components/NoTempoInstanceSelectedState.tsx
- web/src/components/PersesWrapper.tsx
- web/src/components/TempoStackDropdown.tsx
- web/src/hooks/useQueryParam.ts
- web/src/hooks/useTempoStack.ts
- web/src/hooks/useURLState.ts
- web/src/i18n.ts
- web/src/pages/TraceDetailPage.tsx
- web/src/pages/TracesPage/ScatterPlot.tsx
- web/src/pages/TracesPage/TraceTable.tsx
- web/src/pages/TracesPage/TracesPage.tsx
No code changes.
This aligns with the monitoring-plugin and the logging-view-plugin, which use the same max line length.
> increase max line length to increase readability

- web/.eslintrc.yml
- web/package-lock.json
- web/package.json
The react-hooks ESLint linter enforces the rules of hooks and validates the hook dependencies array.
> Enable react-hooks linter

- web/src/components/TempoInstanceDropdown.tsx
Previously, the dropdown was unselected until the list of TempoResources was loaded. With this change, the current instance based on the query params is pre-selected with a slightly inaccurate TempoResourceSelectOption (e.g. list of tenants is inaccurate), which will be replaced with the correct TempoResourceSelectOption once the API call finished.
> Fix flickering in TempoInstance dropdown

- web/src/hooks/useTempoResources.ts
Add error msg if backend service returns invalid response
> Add error msg if backend service returns invalid response

- pkg/proxy/proxy.go
Improve error message if Tempo is not reachable
Before:
After:
> Improve error message if Tempo is not reachable

- web/src/pages/TraceDetailPage.tsx
[OU-518](https://issues.redhat.com//browse/OU-518): Add links to span attributes created by k8sattributeprocessor
> OU-518: Add links to span attributes created by k8sattributeprocessor

- web/package-lock.json
- web/package.json
- web/src/components/PersesWrapper.tsx
- web/src/pages/TraceDetailPage.tsx
- web/src/pages/TracesPage/TraceTable.tsx
Resolves: https://issues.redhat.com/browse/OU-514
Before:
After:
> OU-514: Use PatternFly charts colors

- web/src/pages/TracesPage/QueryBrowser.tsx
- web/src/pages/TracesPage/QueryEditor/QueryEditor.tsx
- web/src/pages/TracesPage/QueryEditor/TraceQLEditor.tsx
Add TraceQL auto-completion and syntax highlighting
Resolves: https://issues.redhat.com/browse/OU-527
> OU-527: Add TraceQL auto-completion and syntax highlighting

- web/src/pages/TracesPage/TraceTable.css
- web/src/pages/TracesPage/TraceTable.tsx
[OU-509](https://issues.redhat.com//browse/OU-509): Style Material UI <Chip> component like PatternFly <Label> component
> OU-509: Style Material UI <Chip> component like PatternFly <Label> component

- web/src/TracingUI.tsx
- web/src/links.ts
- web/src/pages/TraceDetailPage.tsx
- web/src/pages/TracesPage/ScatterPlot.tsx
- web/src/pages/TracesPage/TraceTable.tsx
[OU-516](https://issues.redhat.com//browse/OU-516): Link to Gantt Chart when clicking on a bubble in the ScatterPlot chart
Resolves: https://issues.redhat.com/browse/OU-516
> OU-516: Link to Gantt Chart when clicking on a bubble in the ScatterPlot chart

- go.mod
- go.sum
- pkg/server.go
JIRA
[OU-539](https://issues.redhat.com//browse/OU-539) Reload Certificates : https://issues.redhat.com/browse/OU-539
Mirrors solution from the /monitoring-plugin:
https://github.com/openshift/monitoring-plugin/pull/187/files
> OU-539: Reload plugin certificates

- OWNERS
Adding myself to owners, needed for contributing to the OpenShift CI jobs.
> NO-JIRA: [Chore] Update owners file to add Ishwar from Tracing team

- OWNERS
Update OWNERS file to match main branch.
> COO-362: [Chore] Update OWNERS in release-0.4 branch

- Dockerfile
- tests/cypress.config.ts
- tests/cypress/support/commands.ts
- tests/fixtures/update-plugin-image.sh
- tests/tests/dt-plugin-tests.cy.ts
- tests/views/tour.ts
The PR updates the tests after the filter feature changes.
> [release-0.4] NO-JIRA: [Chore] Update tests after the filter feature.

- web/locales/en/plugin__distributed-tracing-console-plugin.json
- web/package-lock.json
- web/package.json
- web/src/hooks/useTagValues.ts
- web/src/pages/TracesPage/Toolbar/TraceQLEditor.tsx
* update Perses dependencies
* cleanup dependency overwrites
No functional changes.
> NO-JIRA: Update Perses dependencies to 0.51.0

- web/package-lock.json
- web/package.json
> TRACING-5480: Update @mui/x-data-grid

- go.mod
fix https://github.com/openshift/distributed-tracing-console-plugin/pull/144
> OU-675: Add patch version to go 1.24.0
